(defun c:lcha()
  (initget 1)
  (setq pt1 (getpoint "\nClique no primeiro ponto: "))
  (initget 1)
  (setq pt2 (getpoint pt1 "\nClique no segundo ponto: "))
  (initget 1)
  (setq texto (getstring "\nDigite o identificador desejado: "))
  (setq pt3 (polar pt2 ))
)